# Generated by Django 5.0.2 on 2024-03-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountprofilemodel',
            name='company_logo',
            field=models.URLField(blank=True, null=True, verbose_name='company logo'),
        ),
    ]
