# Generated by Django 5.0.2 on 2024-03-22 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_materials', '0002_alter_rawmaterial_natural_origin_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterial',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
