# Generated by Django 5.0.2 on 2024-03-22 22:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_owner_alter_productformula_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='productformularawmaterial',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productformularawmaterial',
            name='edited_on',
            field=models.DateField(auto_now=True),
        ),
    ]
