# Generated by Django 5.0.2 on 2024-03-29 21:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productformularawmaterial_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productformula',
            name='formula_natural_content',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='productformula',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Formula description'),
        ),
        migrations.AlterField(
            model_name='productformula',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.product'),
        ),
    ]
