# Generated by Django 5.0.2 on 2024-03-20 15:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculate_noi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='natural_content',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
