# Generated by Django 5.0.2 on 2024-03-20 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculate_noi', '0002_alter_product_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='productformula',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
