# Generated by Django 5.0.2 on 2024-03-21 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculate_noi', '0004_alter_productformularawmaterial_raw_material'),
        ('raw_materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productformularawmaterial',
            name='raw_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='raw_materials.rawmaterial'),
        ),
    ]
