# Generated by Django 5.0.2 on 2024-03-21 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculate_noi', '0006_alter_productformula_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productformula',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulas', to='calculate_noi.product'),
        ),
    ]
